const { load, check, click, type, key, staticChecks, sectionEndsWithEvidence, done } = require("./harness");
const FILE = "Wk2_Lesson3_Poster_Press.html";
console.log("== " + FILE);
staticChecks(FILE);
const { w, d, errors } = load(FILE);
const $ = s => d.querySelector(s), $$ = s => [...d.querySelectorAll(s)];
check($$(".q").length === 5, "5 warm-up questions");
click($$("#q0 .opt")[0]); check($("#fix0").classList.contains("show"), "wrong warm-up → fix-up");
check($$("#casenotes .remember").length === 2, "2 teaching cards with Remember lines");
check($$("nav.pills a[href^='#']").every(a => d.getElementById(a.getAttribute("href").slice(1))), "nav pills point at real sections");
const gaps = $$(".pline input");
check(gaps.length === 8 && gaps.every(g => g.getAttribute("aria-label")), "8 labelled poster gaps");
check($("#g1").getAttribute("aria-label") === "Gap 2: Every dollar raised goes to ….", "gap 2 label has no space before the full stop");
check($("#printBtn").disabled, "Print locked until every gap has an attempt");
const W = ["community","charity","generosity","justice","dignity","compassion","volunteer","solidarity"];
W.forEach((wd, i) => type(w, gaps[i], wd));
type(w, gaps[2], "generousity"); type(w, gaps[7], "solidarety");
check(!$("#printBtn").disabled, "Print unlocks when all gaps attempted");
click($("#printBtn"));
check(/2 words need fixing/.test($("#printMsg").textContent) && !$("#poster").classList.contains("printed"), "wrong words stop the press");
check(gaps[2].classList.contains("no") && /no u in the middle/.test($("#t2").textContent) && !/generosity/.test($("#t2").textContent) && !/starts with/.test($("#t2").textContent), "wrong gap gets its specific clue");
check(gaps[0].classList.contains("ok") && gaps[0].readOnly, "correct gaps lock green");
check(d.activeElement === gaps[2], "focus moves to first wrong gap");
type(w, gaps[2], "generocity"); click($("#printBtn"));
check(/starts with “gen”/.test($("#t2").textContent), "second miss adds a starting-letters hint");
type(w, gaps[2], "Generosity"); type(w, gaps[7], "solidarity"); click($("#printBtn"));
check($("#poster").classList.contains("printed") && $("#printBtn").disabled, "all correct → poster prints");
click($("#bankBtn")); check($("#bankBox").classList.contains("show") && $("#bankBtn").getAttribute("aria-expanded") === "true", "opt-in word bank opens");
check(!/"> \./.test($("#plines").innerHTML), "no stray space between gap and full stop");
// writing
check($("#exampleBtn").disabled, "worked example locked");
type(w, $("#writebox"), "Our community will show compassion and dignity.");
check(!$("#exampleBtn").disabled && $$("#spy .chip.on").length === 3, "attempt unlocks example; spy counts 3 words");
// dictation
check($("#dictReveal").disabled && $("#dictAnswers").hidden, "dictation answers locked");
$("#dictReady").checked = true; $("#dictReady").dispatchEvent(new w.Event("change"));
click($("#dictReveal"));
check(!$("#dictAnswers").hidden && $$("#dictList li").length === 8, "8 answers shown after ready");
const m = $$(".dmark"); click(m[0]); click(m[3]); click(m[3]); click(m[7]);
check($("#dictScore").textContent === "2", "self-mark score toggles");
const plan = require("./dictation_w2.json");
const shown = $$("#dictList li").map(li => [li.querySelector(".dword").textContent, li.querySelector(".dsent").textContent]);
check(JSON.stringify(shown) === JSON.stringify(plan), "dictation matches unit plan byte-for-byte");
check($$(".check-list label").length === 4, "exit checklist uses full-row labels");
sectionEndsWithEvidence(d, ["briefing", "press", "message", "dictation", "closed"]);
setTimeout(() => { check(errors.length === 0, "zero console/page errors " + (errors.length ? JSON.stringify(errors) : "")); done(); }, 300);
