const { load, check, click, type, key, staticChecks, sectionEndsWithEvidence, done } = require("./harness");
const FILE = "Wk2_Lesson2_Suffix_Machine.html";
console.log("== " + FILE);
staticChecks(FILE);
const { w, d, errors } = load(FILE);
const $ = s => d.querySelector(s), $$ = s => [...d.querySelectorAll(s)];
check($$(".q").length === 5, "5 warm-up questions");
click($$("#q1 .opt")[0]); check($("#fix1").classList.contains("show"), "wrong warm-up → fix-up");
check($$("#casenotes .card").length === 6 && $$("#casenotes .remember").length === 6, "6 teaching cards with Remember lines");
// machine
check($("#mBase").textContent === "donate" && $("#mSuf").textContent === "ion", "machine starts with donate + ion");
check($("#mRun").disabled, "Run locked until a prediction is typed");
type(w, $("#mIn"), "donateion"); check(!$("#mRun").disabled, "typing unlocks Run");
click($("#mRun"));
check($("#mJam").classList.contains("show") && /stuck them straight together/.test($("#mJam").textContent) && /drop the e/.test($("#mJam").textContent), "naive join → specific jam message");
check($("#mNext").hidden, "can't move on after one jam");
type(w, $("#mIn"), "donatin"); key(w, $("#mIn"), "Enter");
check(/jammed twice/.test($("#mJam").textContent) && $$("#mSteps .mstep").length === 3, "second jam reveals the 3 steps");
check(!$("#mNext").hidden && $$(".tchip")[0].classList.contains("rev"), "revealed item marked amber, Next available");
click($("#mNext"));
check($("#mBase").textContent === "generous", "next item loads");
type(w, $("#mIn"), "generousity"); click($("#mRun"));
check(/kept the u/.test($("#mJam").textContent), "kept-u mistake named");
type(w, $("#mIn"), "Generosity"); click($("#mRun"));
check(/Correct prediction/.test($("#mMsg").textContent) && $$("#mSteps .mstep").length === 3, "correct prediction shows steps");
check($$(".tchip")[1].classList.contains("ok"), "correct item marked green");
const OUT = ["equality","celebration","curiosity","collection","purity","action"];
OUT.forEach(o => { click($("#mNext")); type(w, $("#mIn"), o); click($("#mRun")); });
check($$(".tchip.ok").length === 7 && $$(".tchip.rev").length === 1, "7 correct + 1 revealed");
check($("#mNext").textContent === "Finish", "last item shows Finish");
click($("#mNext"));
check(/7 of 8 predicted correctly/.test($("#mMsg").textContent), "finish summary");
// LCWC
check(/Word 1 of 4 · Round 1/.test($("#lcRound").textContent), "LCWC counter shows word x of 4 · round");
check(/Word 1/.test($("#resBody").textContent) && !/generosity/.test($("#resBody").textContent), "results hide spellings until a word is checked");
click($("#coverBtn"));
check($("#lcCover").classList.contains("show") && $$(".stp.now")[0].dataset.s === "cover", "Cover pill lights up");
check($("#lcWord").getAttribute("aria-hidden") === "true", "covered word is hidden from screen readers");
check($("#lcCheck").disabled, "check locked until typed");
type(w, $("#lcIn"), "generousity"); click($("#lcCheck"));
check(/Letters 7 to 11 differ from generosity/.test($("#lcCompareSr").textContent) && !/generosity/.test($("#lcMsg").textContent), "screen-reader text describes the difference");
check(/✗/.test($("#resBody").textContent) && /generosity/.test($("#resBody").textContent), "results record the miss");
const seen = [];
for (let i = 1; i < 8; i++) { click($("#lcNext")); const wd = $("#lcWord").textContent.replace(/\s/g, ""); seen.push(wd); click($("#coverBtn")); type(w, $("#lcIn"), wd); click($("#lcCheck")); }
check(seen[0] === "solidarity" && seen[1] === "compassion" && seen[2] === "dignity", "focus list is generosity, solidarity, compassion, dignity");
check(/Round 2/.test($("#lcRound").textContent) && /Word 4 of 4/.test($("#lcRound").textContent), "reaches word 4 of 4, round 2");
click($("#challengeBtn"));
check(/humanitarian/.test($("#lcWord").textContent.replace(/\s/g,"")) || $("#lcWord").textContent === "humanitarian", "at the end, challenge words continue from where you are (no restart)");
check($$("#resBody tr").length === 6 && /Word 5 of 6/.test($("#lcRound").textContent), "results + counter include challenge words");
click($$("#confi button")[2]); check($$("#confi button")[2].getAttribute("aria-pressed") === "true", "confidence toggles");
sectionEndsWithEvidence(d, ["briefing", "machine", "lcwc", "closed"]);
setTimeout(() => { check(errors.length === 0, "zero console/page errors " + (errors.length ? JSON.stringify(errors) : "")); done(); }, 1500);
